---
user:
  username: "swysocki"
  ssh_pub_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKlnFHI5swpZl5FG+BINqcr0TcAuOhYl9isMxgGyXkFU primary"
  default_shell: "zsh"
  email: "swysocki@gmail.com"
  name: "Scott Wysocki"
repos_path: "devel/repos"
