---
- name: set variables for Linux
  set_fact:
    group_name: "{{ user.username }}"
    home_path: "/home/{{ user.username }}"
    pip_version: "pip3"
    pipx_path: "/home/{{ user.username }}/.local/bin/pipx"

- name: install common tools
  ansible.builtin.package:
    name: "{{ item }}"
  loop:
    - acl
    - fd-find
    - fzf
    - git
    - htop
    - jsonnet
    - nodejs
    - python3-pip
    - python3-venv
    - ripgrep
    - shellcheck
    - tmux
    - virtualenv
    - zsh

- name: install tools with snap
  community.general.snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic }}"
  when: ansible_distribution == "Ubuntu"
  loop:
    - name: "nvim"
      classic: "yes"
    - name: "shfmt"
      classic: "no"

- name: create users
  ansible.builtin.user:
    name: "{{ user.username }}"
    shell: "/bin/{{ user.default_shell }}"
    groups: sudo

- name: set authorized keys
  ansible.posix.authorized_key:
    user: "{{ user.username }}"
    state: present
    key: "{{ user.ssh_pub_key }}"

- name: allow passwordless sudo
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: install pipx using pip
  ansible.builtin.pip:
    name: pipx
    extra_args: --user
  become_user: "{{ user.username }}"
