---
- name: set variables for Mac
  set_fact:
    group_name: staff
    home_path: "/Users/{{ user.username }}"
    pip_version: "pip{{ python_version }}"
    pipx_path: "{{ homebrew_path[ansible_architecture] }}/pipx"
  vars:
    homebrew_path:
      arm64: "/opt/homebrew/bin"
      x86_64: "/usr/local/bin/"

- name: install common tools macos
  community.general.homebrew:
    name: "{{ item }}"
  loop:
    - bash
    - fzf
    - git
    - hadolint
    - jq
    - jsonnet
    - neovim@{{ neovim_version }}
    - pipx
    - pyright
    - python@{{ python_version }}
    - ripgrep
    - shellcheck
    - shfmt
    - tmux
    - tree-sitter
    - virtualenv
    - yamllint
    - zsh
