---
- name: set variables for Linux
  set_fact:
    group_name: "{{ user.username }}"
    home_path: "/home/{{ user.username }}"
    pip_version: "pip3"
    pipx_path: "/usr/bin/pipx"

- name: install common tools
  ansible.builtin.package:
    name: "{{ item }}"
  loop:
    - acl
    - fd-find
    - fzf
    - git
    - htop
    - jsonnet
    - libfuse2
    - pipx
    - python3-pip
    - python3-venv
    - ripgrep
    - shellcheck
    - tmux
    - virtualenv
    - zsh
  become: true

- name: create users
  ansible.builtin.user:
    name: "{{ user.username }}"
    shell: "/bin/{{ user.default_shell }}"
    groups: sudo
  become: true

- name: set authorized keys
  ansible.posix.authorized_key:
    user: "{{ user.username }}"
    state: present
    key: "{{ user.ssh_pub_key }}"

- name: allow passwordless sudo
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  become: true

- name: Create local bin path
  ansible.builtin.file:
    path: "{{ home_path }}/.local/bin"
    state: directory
    owner: "{{ user.username }}"
    group: "{{ group_name }}"

- name: Install neovim from appimage
  ansible.builtin.get_url:
    url: "https://github.com/neovim/neovim/releases/download/v{{ neovim_version }}/nvim.appimage"
    dest: "/home/{{ user.username }}/.local/bin/nvim"
    mode: "755"
    checksum: "sha256:{{ neovim_hash }}"
